### ISSUE TITLE
加载不成功

### ISSUE THREAD

**Issue by liulsg** [17Retoucher/ComfyUI_fooocus_KSample#3]
[ERROR] An error occurred while retrieving information for the 'Fooocus_KSample' node.
Traceback (most recent call last):
  File "D:\AI\ComfyUI_cu121\ComfyUI\server.py", line 420, in get_object_info
    out[x] = node_info(x)
             ^^^^^^^^^^^^
  File "D:\AI\ComfyUI_cu121\ComfyUI\server.py", line 398, in node_info
    info['input'] = obj_class.INPUT_TYPES()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI_cu121\ComfyUI\custom_nodes\ComfyUI_fooocus_KSample\fooocus.py", line 20, in INPUT_TYPES
    "sampler_name": (comfy.samplers.KSampler.SAMPLERS, {"default": "dpmpp_2m_sde_gpu", }),
                     ^^^^^
NameError: name 'comfy' is not defined

**Comment by Elminsst** [comment]
same problem
